name: Initiating Python on GitHub Actions
run-name: ${{ github.actor }} is installing Python and its PIP dependencies 🚀
on:
  workflow_dispatch:
jobs:
  Init-Python:
    runs-on: ubuntu-latest
    steps:
      - name: Preamble logging
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      # If you don't check out files, you will fail at accessing/writing files on repo!
      # SOURCE: https://stackoverflow.com/a/65027251
      - name: Necessary checking out
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Specify the Python version you need
        
      # SOURCE: https://github.com/marketplace/actions/python-dependency-installation
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
        
      - run: echo "🍏 This job's status is ${{ job.status }}."
